"""Fix FK CompraEstoque

Revision ID: 01801562760d
Revises: 24a5973efe0a
Create Date: 2025-11-27 15:16:34.343910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01801562760d'
down_revision = '24a5973efe0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compra_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seriais_xml', sa.Text(), nullable=True))

    with op.batch_alter_table('compra_nf', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pedido_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'pedido_compra', ['pedido_id'], ['id'])

    with op.batch_alter_table('estoque_itens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('compra_item_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'compra_item', ['compra_item_id'], ['id'])

    with op.batch_alter_table('pedido_compra', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=30), nullable=True))
        batch_op.create_index(batch_op.f('ix_pedido_compra_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido_compra', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pedido_compra_status'))
        batch_op.drop_column('status')

    with op.batch_alter_table('estoque_itens', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('compra_item_id')

    with op.batch_alter_table('compra_nf', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('pedido_id')

    with op.batch_alter_table('compra_item', schema=None) as batch_op:
        batch_op.drop_column('seriais_xml')

    # ### end Alembic commands ###
