"""Criar tabelas clientes, vendas e itens_venda

Revision ID: 0f7ebc90cfdf
Revises: 436d028ce3d9
Create Date: 2025-09-16 15:29:21.149603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f7ebc90cfdf'
down_revision = '436d028ce3d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('razao_social', sa.String(length=150), nullable=True),
    sa.Column('sexo', sa.String(length=20), nullable=True),
    sa.Column('profissao', sa.String(length=100), nullable=True),
    sa.Column('documento', sa.String(length=20), nullable=False),
    sa.Column('rg', sa.String(length=20), nullable=True),
    sa.Column('rg_emissor', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('telefone', sa.String(length=30), nullable=True),
    sa.Column('celular', sa.String(length=30), nullable=True),
    sa.Column('endereco', sa.String(length=200), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('cep', sa.String(length=15), nullable=True),
    sa.Column('cr', sa.String(length=50), nullable=True),
    sa.Column('cr_emissor', sa.String(length=50), nullable=True),
    sa.Column('sigma', sa.String(length=50), nullable=True),
    sa.Column('sinarm', sa.String(length=50), nullable=True),
    sa.Column('cac', sa.Boolean(), nullable=True),
    sa.Column('filiado', sa.Boolean(), nullable=True),
    sa.Column('policial', sa.Boolean(), nullable=True),
    sa.Column('bombeiro', sa.Boolean(), nullable=True),
    sa.Column('militar', sa.Boolean(), nullable=True),
    sa.Column('iat', sa.Boolean(), nullable=True),
    sa.Column('psicologo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('documento')
    )
    op.create_table('vendas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('vendedor', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('status_financeiro', sa.String(length=50), nullable=True),
    sa.Column('data_abertura', sa.DateTime(), nullable=True),
    sa.Column('data_fechamento', sa.DateTime(), nullable=True),
    sa.Column('data_quitacao', sa.DateTime(), nullable=True),
    sa.Column('valor_total', sa.Float(), nullable=False),
    sa.Column('nf_numero', sa.String(length=50), nullable=True),
    sa.Column('nf_valor', sa.Float(), nullable=True),
    sa.Column('teve_devolucao', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itens_venda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venda_id', sa.Integer(), nullable=False),
    sa.Column('produto_nome', sa.String(length=200), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('valor_unitario', sa.Float(), nullable=False),
    sa.Column('valor_total', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['venda_id'], ['vendas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itens_venda')
    op.drop_table('vendas')
    op.drop_table('clientes')
    # ### end Alembic commands ###
