"""base inicial locaweb

Revision ID: 154741188876
Revises: 
Create Date: 2025-10-21 09:52:00.475894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '154741188876'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calibre_produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('categoria_produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('pai_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pai_id'], ['categoria_produto.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=True),
    sa.Column('apelido', sa.String(length=100), nullable=True),
    sa.Column('razao_social', sa.String(length=150), nullable=True),
    sa.Column('sexo', sa.String(length=10), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('profissao', sa.String(length=100), nullable=True),
    sa.Column('estado_civil', sa.String(length=50), nullable=True),
    sa.Column('escolaridade', sa.String(length=100), nullable=True),
    sa.Column('naturalidade', sa.String(length=100), nullable=True),
    sa.Column('nacionalidade', sa.String(length=100), nullable=True),
    sa.Column('nome_pai', sa.String(length=150), nullable=True),
    sa.Column('nome_mae', sa.String(length=150), nullable=True),
    sa.Column('matricula', sa.String(length=100), nullable=True),
    sa.Column('documento', sa.String(length=30), nullable=True),
    sa.Column('rg', sa.String(length=30), nullable=True),
    sa.Column('rg_emissor', sa.String(length=100), nullable=True),
    sa.Column('cnh', sa.String(length=30), nullable=True),
    sa.Column('cr', sa.String(length=30), nullable=True),
    sa.Column('cr_emissor', sa.String(length=100), nullable=True),
    sa.Column('data_validade_cr', sa.Date(), nullable=True),
    sa.Column('sigma', sa.String(length=50), nullable=True),
    sa.Column('sinarm', sa.String(length=50), nullable=True),
    sa.Column('inscricao_estadual', sa.String(length=50), nullable=True),
    sa.Column('inscricao_municipal', sa.String(length=50), nullable=True),
    sa.Column('cac', sa.Boolean(), nullable=True),
    sa.Column('filiado', sa.Boolean(), nullable=True),
    sa.Column('policial', sa.Boolean(), nullable=True),
    sa.Column('bombeiro', sa.Boolean(), nullable=True),
    sa.Column('militar', sa.Boolean(), nullable=True),
    sa.Column('iat', sa.Boolean(), nullable=True),
    sa.Column('psicologo', sa.Boolean(), nullable=True),
    sa.Column('atirador_n1', sa.Boolean(), nullable=True),
    sa.Column('atirador_n2', sa.Boolean(), nullable=True),
    sa.Column('atirador_n3', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('documento')
    )
    op.create_table('configuracoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chave', sa.String(length=64), nullable=False),
    sa.Column('valor', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chave')
    )
    op.create_table('funcionamento_produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('marca_produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('taxas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_parcelas', sa.Integer(), nullable=False),
    sa.Column('juros', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipo_produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('armas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('funcionamento', sa.String(length=50), nullable=True),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('modelo', sa.String(length=100), nullable=True),
    sa.Column('calibre', sa.String(length=50), nullable=True),
    sa.Column('numero_serie', sa.String(length=100), nullable=True),
    sa.Column('emissor_craf', sa.String(length=50), nullable=True),
    sa.Column('numero_sigma', sa.String(length=50), nullable=True),
    sa.Column('categoria_adquirente', sa.String(length=60), nullable=True),
    sa.Column('validade_indeterminada', sa.Boolean(), nullable=True),
    sa.Column('data_validade_craf', sa.Date(), nullable=True),
    sa.Column('caminho_craf', sa.Text(), nullable=True),
    sa.Column('data_aquisicao', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_serie')
    )
    op.create_table('clientes_contatos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('valor', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clientes_enderecos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('cep', sa.String(length=20), nullable=True),
    sa.Column('logradouro', sa.String(length=255), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comunicacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('assunto', sa.String(length=150), nullable=True),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('emissor', sa.String(length=50), nullable=True),
    sa.Column('numero_documento', sa.String(length=100), nullable=True),
    sa.Column('data_emissao', sa.Date(), nullable=True),
    sa.Column('data_validade', sa.Date(), nullable=True),
    sa.Column('validade_indeterminada', sa.Boolean(), nullable=False),
    sa.Column('nome_original', sa.Text(), nullable=True),
    sa.Column('caminho_arquivo', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('data_upload', sa.DateTime(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documentos_categoria'), ['categoria'], unique=False)
        batch_op.create_index(batch_op.f('ix_documentos_cliente_id'), ['cliente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documentos_numero_documento'), ['numero_documento'], unique=False)

    op.create_table('notificacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('nivel', sa.String(length=20), nullable=True),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('meio', sa.String(length=20), nullable=True),
    sa.Column('data_envio', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('erro', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedido_compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('data_pedido', sa.Date(), nullable=False),
    sa.Column('cond_pagto', sa.String(length=100), nullable=True),
    sa.Column('modo_desconto', sa.String(length=20), nullable=True),
    sa.Column('percentual_armas', sa.Float(), nullable=True),
    sa.Column('percentual_municoes', sa.Float(), nullable=True),
    sa.Column('percentual_unico', sa.Float(), nullable=True),
    sa.Column('fornecedor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('processos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('marca_id', sa.Integer(), nullable=True),
    sa.Column('calibre_id', sa.Integer(), nullable=True),
    sa.Column('tipo_id', sa.Integer(), nullable=True),
    sa.Column('funcionamento_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=80), nullable=True),
    sa.Column('marca', sa.String(length=80), nullable=True),
    sa.Column('calibre', sa.String(length=50), nullable=True),
    sa.Column('preco_fornecedor', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('desconto_fornecedor', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('frete', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('margem', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ipi', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ipi_tipo', sa.String(length=10), nullable=True),
    sa.Column('difal', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('imposto_venda', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('custo_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('preco_a_vista', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('lucro_liquido_real', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('lucro_alvo', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('preco_final', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['calibre_id'], ['calibre_produto.id'], ),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria_produto.id'], ),
    sa.ForeignKeyConstraint(['funcionamento_id'], ['funcionamento_produto.id'], ),
    sa.ForeignKeyConstraint(['marca_id'], ['marca_produto.id'], ),
    sa.ForeignKeyConstraint(['tipo_id'], ['tipo_produto.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('vendas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('vendedor', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('status_financeiro', sa.String(length=50), nullable=True),
    sa.Column('data_abertura', sa.DateTime(), nullable=True),
    sa.Column('data_fechamento', sa.DateTime(), nullable=True),
    sa.Column('data_quitacao', sa.DateTime(), nullable=True),
    sa.Column('valor_total', sa.Float(), nullable=False),
    sa.Column('nf_numero', sa.String(length=50), nullable=True),
    sa.Column('nf_valor', sa.Float(), nullable=True),
    sa.Column('teve_devolucao', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=True),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('valor_unitario', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido_compra.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itens_venda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venda_id', sa.Integer(), nullable=False),
    sa.Column('produto_nome', sa.String(length=200), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('valor_unitario', sa.Float(), nullable=False),
    sa.Column('valor_total', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['venda_id'], ['vendas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produto_historico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('campo', sa.String(length=100), nullable=False),
    sa.Column('valor_antigo', sa.Text(), nullable=True),
    sa.Column('valor_novo', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('usuario_nome', sa.String(length=120), nullable=True),
    sa.Column('data_modificacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('produto_historico')
    op.drop_table('itens_venda')
    op.drop_table('item_pedido')
    op.drop_table('vendas')
    op.drop_table('produtos')
    op.drop_table('processos')
    op.drop_table('pedido_compra')
    op.drop_table('notificacao')
    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documentos_numero_documento'))
        batch_op.drop_index(batch_op.f('ix_documentos_cliente_id'))
        batch_op.drop_index(batch_op.f('ix_documentos_categoria'))

    op.drop_table('documentos')
    op.drop_table('comunicacoes')
    op.drop_table('clientes_enderecos')
    op.drop_table('clientes_contatos')
    op.drop_table('armas')
    op.drop_table('users')
    op.drop_table('tipo_produto')
    op.drop_table('taxas')
    op.drop_table('marca_produto')
    op.drop_table('funcionamento_produto')
    op.drop_table('configuracoes')
    op.drop_table('clientes')
    op.drop_table('categoria_produto')
    op.drop_table('calibre_produto')
    # ### end Alembic commands ###
