"""Add data_nf

Revision ID: 24a5973efe0a
Revises: 9a2e35a14b66
Create Date: 2025-11-27 14:11:41.261478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24a5973efe0a'
down_revision = '9a2e35a14b66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estoque_itens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_nf', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estoque_itens', schema=None) as batch_op:
        batch_op.drop_column('data_nf')

    # ### end Alembic commands ###
