"""initial migration

Revision ID: 24bff361c8c7
Revises: 
Create Date: 2025-09-24 19:10:47.126012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24bff361c8c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_nascimento', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('nome_pai', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('nome_mae', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('apelido', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('estado_civil', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('escolaridade', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('naturalidade', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cnh', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_column('cnh')
        batch_op.drop_column('naturalidade')
        batch_op.drop_column('escolaridade')
        batch_op.drop_column('estado_civil')
        batch_op.drop_column('apelido')
        batch_op.drop_column('nome_mae')
        batch_op.drop_column('nome_pai')
        batch_op.drop_column('data_nascimento')

    # ### end Alembic commands ###
