"""Check para exibição de categoria

Revision ID: 406ff92e16ed
Revises: f62c3ece2226
Create Date: 2026-02-18 17:07:10.459937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '406ff92e16ed'
down_revision = 'f62c3ece2226'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categoria_produto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exibir_no_menu', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categoria_produto', schema=None) as batch_op:
        batch_op.drop_column('exibir_no_menu')

    # ### end Alembic commands ###
