"""add data_validade_cr to clientes

Revision ID: 41d107842e51
Revises: d43086ec3a7f
Create Date: 2025-09-27 11:39:59.406418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41d107842e51'
down_revision = 'd43086ec3a7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_validade_cr', sa.Date(), nullable=True))

    with op.batch_alter_table('comunicacoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assunto', sa.String(length=150), nullable=True))

    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('validade', sa.Date(), nullable=True))
        batch_op.drop_constraint(batch_op.f('documentos_usuario_id_fkey'), type_='foreignkey')
        batch_op.drop_column('usuario_id')

    with op.batch_alter_table('itens_venda', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('itens_venda_venda_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'vendas', ['venda_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.alter_column('ipi_tipo',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=15),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.alter_column('ipi_tipo',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    with op.batch_alter_table('itens_venda', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('itens_venda_venda_id_fkey'), 'vendas', ['venda_id'], ['id'])

    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('documentos_usuario_id_fkey'), 'users', ['usuario_id'], ['id'])
        batch_op.drop_column('validade')

    with op.batch_alter_table('comunicacoes', schema=None) as batch_op:
        batch_op.drop_column('assunto')

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_column('data_validade_cr')

    # ### end Alembic commands ###
