"""add configuracao table

Revision ID: 436d028ce3d9
Revises: 
Create Date: 2025-09-12 19:33:44.623677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '436d028ce3d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chave', sa.String(length=64), nullable=False),
    sa.Column('valor', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chave')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configuracao')
    # ### end Alembic commands ###
