"""corrigir relacionamento pedido->cliente

Revision ID: 4628e62331a4
Revises: 52fa41905969
Create Date: 2025-09-17 16:46:17.739134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4628e62331a4'
down_revision = '52fa41905969'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedido_compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('data_pedido', sa.Date(), nullable=False),
    sa.Column('cond_pagto', sa.String(length=100), nullable=True),
    sa.Column('modo_desconto', sa.String(length=20), nullable=True),
    sa.Column('percentual_armas', sa.Float(), nullable=True),
    sa.Column('percentual_municoes', sa.Float(), nullable=True),
    sa.Column('percentual_unico', sa.Float(), nullable=True),
    sa.Column('fornecedor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('item_pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=True),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('valor_unitario', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido_compra.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_pedido')
    op.drop_table('pedido_compra')
    # ### end Alembic commands ###
