"""add tipo_marca_calibre_to_produtos

Revision ID: 49b66cf47e19
Revises: 9b949b7a3193
Create Date: 2025-10-16 11:53:55.235281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49b66cf47e19'
down_revision = '9b949b7a3193'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('marca', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('calibre', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_column('calibre')
        batch_op.drop_column('marca')
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###
