"""Add cnpj fornecedor

Revision ID: 57a73e74be66
Revises: ffeeb56c244c
Create Date: 2025-11-28 09:35:50.732218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57a73e74be66'
down_revision = 'ffeeb56c244c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compra_nf', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cnpj_fornecedor', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compra_nf', schema=None) as batch_op:
        batch_op.drop_column('cnpj_fornecedor')

    # ### end Alembic commands ###
