"""add certidoes module

Revision ID: 5f20b45bdd53
Revises: c75122bda705
Create Date: 2025-12-06 09:46:32.520971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f20b45bdd53'
down_revision = 'c75122bda705'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certidoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('ESTADUAL_TJPI', 'MILITAR_STM', 'ELEITORAL_TSE', 'FEDERAL_TRF1', name='certidao_tipo_enum'), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'EM_PROCESSO', 'EMITIDA', 'ERRO', 'CANCELADA', name='certidao_status_enum'), nullable=False),
    sa.Column('data_solicitacao', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_emissao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('validade_ate', sa.Date(), nullable=True),
    sa.Column('url_portal', sa.String(length=255), nullable=True),
    sa.Column('arquivo_storage_key', sa.String(length=255), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('criado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['criado_por_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('arquivo_storage_key')
    )
    with op.batch_alter_table('certidoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certidoes_cliente_id'), ['cliente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_certidoes_criado_por_id'), ['criado_por_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_certidoes_data_emissao'), ['data_emissao'], unique=False)
        batch_op.create_index(batch_op.f('ix_certidoes_data_solicitacao'), ['data_solicitacao'], unique=False)
        batch_op.create_index(batch_op.f('ix_certidoes_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_certidoes_tipo'), ['tipo'], unique=False)
        batch_op.create_index(batch_op.f('ix_certidoes_validade_ate'), ['validade_ate'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certidoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certidoes_validade_ate'))
        batch_op.drop_index(batch_op.f('ix_certidoes_tipo'))
        batch_op.drop_index(batch_op.f('ix_certidoes_status'))
        batch_op.drop_index(batch_op.f('ix_certidoes_data_solicitacao'))
        batch_op.drop_index(batch_op.f('ix_certidoes_data_emissao'))
        batch_op.drop_index(batch_op.f('ix_certidoes_criado_por_id'))
        batch_op.drop_index(batch_op.f('ix_certidoes_cliente_id'))

    op.drop_table('certidoes')
    # ### end Alembic commands ###
