"""Add campos promocao

Revision ID: 60fbc7e8efba
Revises: 8ce63c7bc78d
Create Date: 2025-11-27 10:10:17.739973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60fbc7e8efba'
down_revision = '8ce63c7bc78d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('promo_ativada', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('promo_preco_fornecedor', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('promo_data_inicio', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('promo_data_fim', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_produtos_promo_ativada'), ['promo_ativada'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_produtos_promo_ativada'))
        batch_op.drop_column('promo_data_fim')
        batch_op.drop_column('promo_data_inicio')
        batch_op.drop_column('promo_preco_fornecedor')
        batch_op.drop_column('promo_ativada')

    # ### end Alembic commands ###
