"""expandir produtos + categorias + histórico

Revision ID: 63b5f4afb925
Revises: c99999999999
Create Date: 2025-10-14 16:16:57.675397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63b5f4afb925'
down_revision = 'c99999999999'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria_produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('nivel', sa.SmallInteger(), nullable=False),
    sa.Column('pai_id', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pai_id'], ['categoria_produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produto_historico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('campo', sa.String(length=50), nullable=False),
    sa.Column('valor_antigo', sa.String(length=255), nullable=True),
    sa.Column('valor_novo', sa.String(length=255), nullable=True),
    sa.Column('data_alteracao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notificacao', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('mensagem',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_notif_cliente_tipo_msg_data_dia'))
        batch_op.drop_index(batch_op.f('ix_notif_cliente_tipo_status_data'))

    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codigo', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('marca', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('modelo', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('categoria_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ativo', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('imagem_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('quantidade', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('estoque_minimo', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('alerta_estoque', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('criado_em', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('atualizado_em', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'categoria_produto', ['categoria_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('atualizado_em')
        batch_op.drop_column('criado_em')
        batch_op.drop_column('alerta_estoque')
        batch_op.drop_column('estoque_minimo')
        batch_op.drop_column('quantidade')
        batch_op.drop_column('imagem_url')
        batch_op.drop_column('ativo')
        batch_op.drop_column('categoria_id')
        batch_op.drop_column('modelo')
        batch_op.drop_column('marca')
        batch_op.drop_column('codigo')

    with op.batch_alter_table('notificacao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notif_cliente_tipo_status_data'), ['cliente_id', 'tipo', 'status', 'data_envio'], unique=False)
        batch_op.create_index(batch_op.f('ix_notif_cliente_tipo_msg_data_dia'), ['cliente_id', 'tipo', 'mensagem', sa.literal_column('date(data_envio)')], unique=False)
        batch_op.alter_column('mensagem',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    op.drop_table('produto_historico')
    op.drop_table('categoria_produto')
    # ### end Alembic commands ###
