"""Autenticação Clientes

Revision ID: 6f927cdcc5e2
Revises: d5f3b4d2aa93
Create Date: 2026-03-04 17:54:21.679196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f927cdcc5e2'
down_revision = 'd5f3b4d2aa93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_login', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('senha_hash', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('ativo_loja', sa.Boolean(), nullable=False, server_default='true'))
        batch_op.add_column(sa.Column('email_verificado', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.add_column(sa.Column('loja_criado_em', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_clientes_email_login'), ['email_login'], unique=True)

    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pago_em', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_column('pago_em')

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clientes_email_login'))
        batch_op.drop_column('loja_criado_em')
        batch_op.drop_column('email_verificado')
        batch_op.drop_column('ativo_loja')
        batch_op.drop_column('senha_hash')
        batch_op.drop_column('email_login')

    # ### end Alembic commands ###
