"""Rename total to valor_total in compra_nf

Revision ID: 7430f6ae9a85
Revises: da094699375c
Create Date: 2025-10-29 10:38:36.053342

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7430f6ae9a85'
down_revision = 'da094699375c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compra_nf', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valor_total', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.drop_constraint(batch_op.f('compra_nf_chave_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_compra_nf_chave'), ['chave'], unique=True)
        batch_op.drop_column('total')

    with op.batch_alter_table('produto_historico', schema=None) as batch_op:
        batch_op.alter_column('data_modificacao',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto_historico', schema=None) as batch_op:
        batch_op.alter_column('data_modificacao',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('compra_nf', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_compra_nf_chave'))
        batch_op.create_unique_constraint(batch_op.f('compra_nf_chave_key'), ['chave'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('valor_total')

    # ### end Alembic commands ###
