"""ajuste EnderecoCliente add logradouro

Revision ID: 7981c57e9c70
Revises: 8e23965ab519
Create Date: 2025-09-29 16:03:11.957143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7981c57e9c70'
down_revision = '8e23965ab519'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes_enderecos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logradouro', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes_enderecos', schema=None) as batch_op:
        batch_op.drop_column('logradouro')

    # ### end Alembic commands ###
