"""create table notificacao

Revision ID: 7ab33c8dcbc2
Revises: 8d3a42c9a6f4
Create Date: 2025-10-13 11:51:29.597994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ab33c8dcbc2'
down_revision = '8d3a42c9a6f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.alter_column('cliente_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_documentos_cliente_id'), ['cliente_id'], unique=False)
        batch_op.drop_column('validade')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('validade', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_documentos_cliente_id'))
        batch_op.alter_column('cliente_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
