"""create table armas

Revision ID: 7e609914eb84
Revises: 24bff361c8c7
Create Date: 2025-09-25 09:13:58.916258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e609914eb84'
down_revision = '24bff361c8c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('armas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('modelo', sa.String(length=100), nullable=True),
    sa.Column('calibre', sa.String(length=50), nullable=True),
    sa.Column('numero_serie', sa.String(length=100), nullable=True),
    sa.Column('craf', sa.String(length=50), nullable=True),
    sa.Column('data_aquisicao', sa.Date(), nullable=True),
    sa.Column('data_validade_craf', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_serie')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('armas')
    # ### end Alembic commands ###
