"""adiciona logo_url em marca_produto

Revision ID: 82fb0e611903
Revises: 23ae69b9bb78
Create Date: 2026-02-17 18:45:12.754826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82fb0e611903'
down_revision = '23ae69b9bb78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marca_produto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_url', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marca_produto', schema=None) as batch_op:
        batch_op.drop_column('logo_url')

    # ### end Alembic commands ###
