"""add descricao to categoria_produto

Revision ID: 8506a84073d8
Revises: 86939dcad16a
Create Date: 2025-10-15 10:54:51.489893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8506a84073d8'
down_revision = '86939dcad16a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categoria_produto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descricao', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('criado_em', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('atualizado_em', sa.DateTime(), nullable=True))
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               nullable=False)
        batch_op.create_unique_constraint(None, ['nome'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categoria_produto', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('nome',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('atualizado_em')
        batch_op.drop_column('criado_em')
        batch_op.drop_column('descricao')

    # ### end Alembic commands ###
