"""Adiciona item_estoque_id em ItemVenda

Revision ID: 893241ee7d69
Revises: 318aba777f81
Create Date: 2025-11-24 17:08:17.264288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '893241ee7d69'
down_revision = '318aba777f81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itens_venda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_estoque_id', sa.Integer(), nullable=True))
        batch_op.alter_column('valor_unitario',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('valor_total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'estoque_itens', ['item_estoque_id'], ['id'])

    with op.batch_alter_table('produto_historico', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_historico_data_modificacao'))
        batch_op.drop_index(batch_op.f('idx_historico_origem'))
        batch_op.drop_index(batch_op.f('idx_historico_produto_id'))
        batch_op.drop_index(batch_op.f('idx_historico_usuario_id'))
        batch_op.create_index(batch_op.f('ix_produto_historico_data_modificacao'), ['data_modificacao'], unique=False)
        batch_op.create_index(batch_op.f('ix_produto_historico_origem'), ['origem'], unique=False)
        batch_op.create_index(batch_op.f('ix_produto_historico_produto_id'), ['produto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_produto_historico_usuario_id'), ['usuario_id'], unique=False)

    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_produto_atualizado_em'))
        batch_op.drop_index(batch_op.f('idx_produto_criado_em'))
        batch_op.drop_constraint(batch_op.f('produtos_codigo_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_produtos_atualizado_em'), ['atualizado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_produtos_calibre_id'), ['calibre_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_produtos_categoria_id'), ['categoria_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_produtos_codigo'), ['codigo'], unique=True)
        batch_op.create_index(batch_op.f('ix_produtos_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_produtos_marca_id'), ['marca_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_produtos_nome'), ['nome'], unique=False)
        batch_op.create_index(batch_op.f('ix_produtos_tipo_id'), ['tipo_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_produtos_tipo_id'))
        batch_op.drop_index(batch_op.f('ix_produtos_nome'))
        batch_op.drop_index(batch_op.f('ix_produtos_marca_id'))
        batch_op.drop_index(batch_op.f('ix_produtos_criado_em'))
        batch_op.drop_index(batch_op.f('ix_produtos_codigo'))
        batch_op.drop_index(batch_op.f('ix_produtos_categoria_id'))
        batch_op.drop_index(batch_op.f('ix_produtos_calibre_id'))
        batch_op.drop_index(batch_op.f('ix_produtos_atualizado_em'))
        batch_op.create_unique_constraint(batch_op.f('produtos_codigo_key'), ['codigo'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('idx_produto_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('idx_produto_atualizado_em'), ['atualizado_em'], unique=False)

    with op.batch_alter_table('produto_historico', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_produto_historico_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_produto_historico_produto_id'))
        batch_op.drop_index(batch_op.f('ix_produto_historico_origem'))
        batch_op.drop_index(batch_op.f('ix_produto_historico_data_modificacao'))
        batch_op.create_index(batch_op.f('idx_historico_usuario_id'), ['usuario_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_historico_produto_id'), ['produto_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_historico_origem'), ['origem'], unique=False)
        batch_op.create_index(batch_op.f('idx_historico_data_modificacao'), ['data_modificacao'], unique=False)

    with op.batch_alter_table('itens_venda', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('valor_total',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
        batch_op.alter_column('valor_unitario',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
        batch_op.drop_column('item_estoque_id')

    # ### end Alembic commands ###
