"""add modelo documento

Revision ID: 8ce63c7bc78d
Revises: 90aedeff9619
Create Date: 2025-11-26 17:37:50.530950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ce63c7bc78d'
down_revision = '90aedeff9619'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modelos_documento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('chave', sa.String(length=50), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chave')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('modelos_documento')
    # ### end Alembic commands ###
