"""ajustes Cliente + enderecos + contatos

Revision ID: 8e23965ab519
Revises: 41d107842e51
Create Date: 2025-09-29 12:00:44.431656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e23965ab519'
down_revision = '41d107842e51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes_contatos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('valor', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clientes_enderecos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('cep', sa.String(length=20), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('rua', sa.String(length=255), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nacionalidade', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('matricula', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('inscricao_estadual', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('inscricao_municipal', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('atirador_n1', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('atirador_n2', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('atirador_n3', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_column('atirador_n3')
        batch_op.drop_column('atirador_n2')
        batch_op.drop_column('atirador_n1')
        batch_op.drop_column('inscricao_municipal')
        batch_op.drop_column('inscricao_estadual')
        batch_op.drop_column('matricula')
        batch_op.drop_column('nacionalidade')

    op.drop_table('clientes_enderecos')
    op.drop_table('clientes_contatos')
    # ### end Alembic commands ###
