"""Criação do módulo de carrinho

Revision ID: 8f9c5145989a
Revises: a17be3d40aed
Create Date: 2026-03-02 15:42:16.255014

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8f9c5145989a'
down_revision = 'a17be3d40aed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carrinhos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('carrinhos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_carrinhos_session_id'), ['session_id'], unique=False)

    op.create_table('carrinho_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carrinho_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('preco_unitario_no_momento', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['carrinho_id'], ['carrinhos.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categoria_produto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_categoria_slug'))

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clientes_email_login'))
        batch_op.drop_column('aceitou_termos')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('email_login')
        batch_op.drop_column('ativo')
        batch_op.drop_column('ultimo_login')

    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_produto_preco'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_produto_preco'), ['preco_a_vista'], unique=False)

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ultimo_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ativo', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('email_login', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('aceitou_termos', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_clientes_email_login'), ['email_login'], unique=True)

    with op.batch_alter_table('categoria_produto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_categoria_slug'), ['slug'], unique=False)

    op.drop_table('carrinho_items')
    with op.batch_alter_table('carrinhos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_carrinhos_session_id'))

    op.drop_table('carrinhos')
    # ### end Alembic commands ###
