"""empty message

Revision ID: 90aedeff9619
Revises: a6910bada999
Create Date: 2025-11-25 11:13:23.860679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90aedeff9619'
down_revision = 'a6910bada999'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estoque_itens', schema=None) as batch_op:
        batch_op.alter_column('numero_embalagem',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_estoque_itens_numero_embalagem'), ['numero_embalagem'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estoque_itens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_estoque_itens_numero_embalagem'))
        batch_op.alter_column('numero_embalagem',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
