"""ajustes ecommerce mahrte style

Revision ID: 92f37c8838cd
Revises: 9c5d4692674e
Create Date: 2026-02-16 14:58:24.302812

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '92f37c8838cd'
down_revision = '9c5d4692674e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categoria_produto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('icone_loja', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('ordem_exibicao', sa.Integer(), nullable=True))
        batch_op.alter_column('criado_em',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('atualizado_em',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_categoria_produto_slug'), ['slug'], unique=True)

    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eh_lancamento', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('eh_outdoor', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('requer_documentacao', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('descricao_comercial', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_produtos_requer_documentacao'), ['requer_documentacao'], unique=False)
        batch_op.drop_column('marca')
        batch_op.drop_column('tipo')
        batch_op.drop_column('calibre')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calibre', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tipo', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('marca', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_produtos_requer_documentacao'))
        batch_op.drop_column('descricao_comercial')
        batch_op.drop_column('requer_documentacao')
        batch_op.drop_column('eh_outdoor')
        batch_op.drop_column('eh_lancamento')

    with op.batch_alter_table('categoria_produto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categoria_produto_slug'))
        batch_op.alter_column('atualizado_em',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('criado_em',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.drop_column('ordem_exibicao')
        batch_op.drop_column('icone_loja')
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
