"""empty message

Revision ID: 9a2e35a14b66
Revises: 60fbc7e8efba
Create Date: 2025-11-27 13:27:29.978870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a2e35a14b66'
down_revision = '60fbc7e8efba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estoque_itens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nota_fiscal', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estoque_itens', schema=None) as batch_op:
        batch_op.drop_column('nota_fiscal')

    # ### end Alembic commands ###
