"""add pai_id and descricao to categoria_produto

Revision ID: 9b949b7a3193
Revises: 8506a84073d8
Create Date: 2025-10-15 11:10:02.812921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b949b7a3193'
down_revision = '8506a84073d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categoria_produto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pai_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'categoria_produto', ['pai_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categoria_produto', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('pai_id')

    # ### end Alembic commands ###
