"""add ecommerce fields to produto

Revision ID: 9c5d4692674e
Revises: 5f20b45bdd53
Create Date: 2026-02-13 16:11:48.863527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c5d4692674e'
down_revision = '5f20b45bdd53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('visivel_loja', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('estoque_disponivel', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('destaque_home', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('meta_title', sa.String(length=70), nullable=True))
        batch_op.add_column(sa.Column('meta_description', sa.String(length=160), nullable=True))
        batch_op.add_column(sa.Column('tags_palavras_chave', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('descricao_longa', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('especificacoes_tecnicas', sa.JSON(), nullable=True))
        batch_op.create_index('idx_produto_slug', ['slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_produtos_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_produtos_visivel_loja'), ['visivel_loja'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_produtos_visivel_loja'))
        batch_op.drop_index(batch_op.f('ix_produtos_slug'))
        batch_op.drop_index('idx_produto_slug')
        batch_op.drop_column('especificacoes_tecnicas')
        batch_op.drop_column('descricao_longa')
        batch_op.drop_column('tags_palavras_chave')
        batch_op.drop_column('meta_description')
        batch_op.drop_column('meta_title')
        batch_op.drop_column('destaque_home')
        batch_op.drop_column('estoque_disponivel')
        batch_op.drop_column('visivel_loja')
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
