"""add auth fields to cliente

Revision ID: a17be3d40aed
Revises: 406ff92e16ed
Create Date: 2026-02-20 18:12:45.658144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a17be3d40aed'
down_revision = '406ff92e16ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_login', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('ativo', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('ultimo_login', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('aceitou_termos', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_clientes_email_login'), ['email_login'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clientes_email_login'))
        batch_op.drop_column('aceitou_termos')
        batch_op.drop_column('ultimo_login')
        batch_op.drop_column('ativo')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('email_login')

    # ### end Alembic commands ###
