"""Venda_Municao

Revision ID: a6910bada999
Revises: 893241ee7d69
Create Date: 2025-11-24 17:29:08.774829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6910bada999'
down_revision = '893241ee7d69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendas_anexos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venda_id', sa.Integer(), nullable=False),
    sa.Column('tipo_documento', sa.String(length=50), nullable=False),
    sa.Column('nome_arquivo', sa.String(length=255), nullable=False),
    sa.Column('url_arquivo', sa.String(length=500), nullable=False),
    sa.Column('metadados', sa.JSON(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('enviado_por', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['venda_id'], ['vendas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('itens_venda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('arma_cliente_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'armas', ['arma_cliente_id'], ['id'])

    with op.batch_alter_table('vendas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_processo', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('etapa', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('data_entrega_efetiva', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('retirado_por', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('observacoes', sa.Text(), nullable=True))
        batch_op.alter_column('valor_total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('desconto_valor',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('valor_recebido',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('valor_faltante',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('nf_valor',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_vendas_etapa'), ['etapa'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendas_etapa'))
        batch_op.alter_column('nf_valor',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('valor_faltante',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('valor_recebido',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('desconto_valor',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('valor_total',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.drop_column('observacoes')
        batch_op.drop_column('retirado_por')
        batch_op.drop_column('data_entrega_efetiva')
        batch_op.drop_column('etapa')
        batch_op.drop_column('tipo_processo')

    with op.batch_alter_table('itens_venda', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('arma_cliente_id')

    op.drop_table('vendas_anexos')
    # ### end Alembic commands ###
