"""criar tabela estoque_itens

Revision ID: b671cf012a12
Revises: 7430f6ae9a85
Create Date: 2025-10-29 17:02:16.402476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b671cf012a12'
down_revision = '7430f6ae9a85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estoque_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('numero_serie', sa.String(length=100), nullable=True),
    sa.Column('numero_embalagem', sa.String(length=100), nullable=True),
    sa.Column('lote', sa.String(length=100), nullable=True),
    sa.Column('quantidade_embalagem', sa.Integer(), nullable=True),
    sa.Column('quantidade_disponivel', sa.Integer(), nullable=True),
    sa.Column('nf_compra', sa.String(length=44), nullable=True),
    sa.Column('pedido_compra_id', sa.Integer(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('data_recebimento', sa.DateTime(), nullable=True),
    sa.Column('data_venda', sa.DateTime(), nullable=True),
    sa.Column('data_entrega', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_serie')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('estoque_itens')
    # ### end Alembic commands ###
