"""add relations marca_id, calibre_id, tipo_id, funcionamento_id to produtos

Revision ID: c5c3a2dadeab
Revises: 6d2671c03d9a
Create Date: 2025-10-16 14:52:11.195569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5c3a2dadeab'
down_revision = '6d2671c03d9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marca_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('calibre_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tipo_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('funcionamento_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'funcionamento_produto', ['funcionamento_id'], ['id'])
        batch_op.create_foreign_key(None, 'tipo_produto', ['tipo_id'], ['id'])
        batch_op.create_foreign_key(None, 'marca_produto', ['marca_id'], ['id'])
        batch_op.create_foreign_key(None, 'calibre_produto', ['calibre_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('funcionamento_id')
        batch_op.drop_column('tipo_id')
        batch_op.drop_column('calibre_id')
        batch_op.drop_column('marca_id')

    # ### end Alembic commands ###
