"""create table notificacao (fix location)

Revision ID: c73fbe572f2e
Revises: 7ab33c8dcbc2
Create Date: 2025-10-13 14:42:43.677158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c73fbe572f2e'
down_revision = '7ab33c8dcbc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notificacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('nivel', sa.String(length=20), nullable=True),
    sa.Column('mensagem', sa.String(length=255), nullable=True),
    sa.Column('meio', sa.String(length=20), nullable=True),
    sa.Column('data_envio', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('erro', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notificacao')
    # ### end Alembic commands ###
