"""Add embalagem e auto-link

Revision ID: c75122bda705
Revises: f01e02ff7b8b
Create Date: 2025-11-28 11:53:27.042236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c75122bda705'
down_revision = 'f01e02ff7b8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compra_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero_embalagem', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compra_item', schema=None) as batch_op:
        batch_op.drop_column('numero_embalagem')

    # ### end Alembic commands ###
