"""Criação do Pedido Pagar.me

Revision ID: c83acc43ab14
Revises: 8f9c5145989a
Create Date: 2026-03-02 16:13:31.430475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c83acc43ab14'
down_revision = '8f9c5145989a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('nome_cliente', sa.String(length=100), nullable=False),
    sa.Column('email_cliente', sa.String(length=100), nullable=False),
    sa.Column('documento', sa.String(length=20), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('cep', sa.String(length=10), nullable=False),
    sa.Column('logradouro', sa.String(length=255), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('bairro', sa.String(length=100), nullable=False),
    sa.Column('cidade', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=2), nullable=False),
    sa.Column('total_produtos', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_frete', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_pedido', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('forma_pagamento', sa.String(length=20), nullable=True),
    sa.Column('parcelas', sa.Integer(), nullable=True),
    sa.Column('pagarme_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pedidos_pagarme_id'), ['pagarme_id'], unique=False)

    op.create_table('pedido_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_unitario_historico', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pedido_items')
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pedidos_pagarme_id'))

    op.drop_table('pedidos')
    # ### end Alembic commands ###
