"""add caminho_craf to armas

Revision ID: d43086ec3a7f
Revises: 7e609914eb84
Create Date: 2025-09-25 11:05:28.378175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd43086ec3a7f'
down_revision = '7e609914eb84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('armas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caminho_craf', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('armas', schema=None) as batch_op:
        batch_op.drop_column('caminho_craf')

    # ### end Alembic commands ###
