"""Informações para frete

Revision ID: d5f3b4d2aa93
Revises: c83acc43ab14
Create Date: 2026-03-02 16:29:44.837330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5f3b4d2aa93'
down_revision = 'c83acc43ab14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('peso', sa.Numeric(precision=10, scale=3), nullable=True))
        batch_op.add_column(sa.Column('comprimento', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('largura', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('altura', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_column('altura')
        batch_op.drop_column('largura')
        batch_op.drop_column('comprimento')
        batch_op.drop_column('peso')

    # ### end Alembic commands ###
