"""Atualiza modelo de vendas com novos campos

Revision ID: ec3eef5b0192
Revises: a9686b3ce01d
Create Date: 2025-11-10 16:37:08.095822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec3eef5b0192'
down_revision = 'a9686b3ce01d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_clientes_nome'))

    with op.batch_alter_table('importacoes_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_importacoes_log_data_hora'))
        batch_op.drop_index(batch_op.f('idx_importacoes_log_tipo'))

    with op.batch_alter_table('itens_venda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sku', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('produto_id', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('idx_itemvenda_produto_nome'))
        batch_op.drop_index(batch_op.f('idx_itemvenda_venda_id'))
        batch_op.create_foreign_key(None, 'produtos', ['produto_id'], ['id'])

    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_produtos_atualizado_em'))
        batch_op.drop_index(batch_op.f('idx_produtos_categoria_id'))
        batch_op.drop_index(batch_op.f('idx_produtos_nome'))

    with op.batch_alter_table('vendas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caixa', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('data_cancelamento', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('desconto_valor', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('desconto_percentual', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('valor_recebido', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('valor_faltante', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('crediario', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('parcelas_qtd', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('parcelas_primeiro_vencimento', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('parcelas_ultimo_vencimento', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('nf_data', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('cliente_nome', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('documento_cliente', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('tipo_pessoa', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('qtd_total_itens', sa.Integer(), nullable=True))
        batch_op.alter_column('cliente_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('valor_total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.drop_index(batch_op.f('idx_vendas_cliente_id'))
        batch_op.drop_index(batch_op.f('idx_vendas_data_abertura'))
        batch_op.drop_index(batch_op.f('idx_vendas_valor_total'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_vendas_valor_total'), ['valor_total'], unique=False)
        batch_op.create_index(batch_op.f('idx_vendas_data_abertura'), ['data_abertura'], unique=False)
        batch_op.create_index(batch_op.f('idx_vendas_cliente_id'), ['cliente_id'], unique=False)
        batch_op.alter_column('valor_total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('cliente_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('qtd_total_itens')
        batch_op.drop_column('tipo_pessoa')
        batch_op.drop_column('documento_cliente')
        batch_op.drop_column('cliente_nome')
        batch_op.drop_column('nf_data')
        batch_op.drop_column('parcelas_ultimo_vencimento')
        batch_op.drop_column('parcelas_primeiro_vencimento')
        batch_op.drop_column('parcelas_qtd')
        batch_op.drop_column('crediario')
        batch_op.drop_column('valor_faltante')
        batch_op.drop_column('valor_recebido')
        batch_op.drop_column('desconto_percentual')
        batch_op.drop_column('desconto_valor')
        batch_op.drop_column('data_cancelamento')
        batch_op.drop_column('caixa')

    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_produtos_nome'), ['nome'], unique=False)
        batch_op.create_index(batch_op.f('idx_produtos_categoria_id'), ['categoria_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_produtos_atualizado_em'), ['atualizado_em'], unique=False)

    with op.batch_alter_table('itens_venda', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('idx_itemvenda_venda_id'), ['venda_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_itemvenda_produto_nome'), ['produto_nome'], unique=False)
        batch_op.drop_column('produto_id')
        batch_op.drop_column('sku')

    with op.batch_alter_table('importacoes_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_importacoes_log_tipo'), ['tipo'], unique=False)
        batch_op.create_index(batch_op.f('idx_importacoes_log_data_hora'), [sa.literal_column('data_hora DESC')], unique=False)

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_clientes_nome'), ['nome'], unique=False)

    # ### end Alembic commands ###
