"""Add GT global e auto-link

Revision ID: f01e02ff7b8b
Revises: 57a73e74be66
Create Date: 2025-11-28 11:17:48.249298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f01e02ff7b8b'
down_revision = '57a73e74be66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compra_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codigo_produto_xml', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('produto_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'produtos', ['produto_id'], ['id'])

    with op.batch_alter_table('compra_nf', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guia_transito_file', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('numero_selo', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compra_nf', schema=None) as batch_op:
        batch_op.drop_column('numero_selo')
        batch_op.drop_column('guia_transito_file')

    with op.batch_alter_table('compra_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('produto_id')
        batch_op.drop_column('codigo_produto_xml')

    # ### end Alembic commands ###
