"""Add arma fields: tipo, funcionamento, emissor_craf, numero_sigma, categoria_adquirente, validade_indeterminada

Revision ID: f07a79e2c320
Revises: a929b4bd986e
Create Date: 2025-10-03 16:33:09.186797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f07a79e2c320'
down_revision = 'a929b4bd986e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('armas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('funcionamento', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('emissor_craf', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('numero_sigma', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('categoria_adquirente', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('validade_indeterminada', sa.Boolean(), nullable=True))
        batch_op.drop_column('craf')

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)

    with op.batch_alter_table('clientes_enderecos', schema=None) as batch_op:
        batch_op.drop_column('ignorado')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes_enderecos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ignorado', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)

    with op.batch_alter_table('armas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('craf', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_column('validade_indeterminada')
        batch_op.drop_column('categoria_adquirente')
        batch_op.drop_column('numero_sigma')
        batch_op.drop_column('emissor_craf')
        batch_op.drop_column('funcionamento')
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###
