"""Add nome_comercial and expand meta_description

Revision ID: f62c3ece2226
Revises: 82fb0e611903
Create Date: 2026-02-18 14:23:49.433160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f62c3ece2226'
down_revision = '82fb0e611903'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome_comercial', sa.String(length=255), nullable=True))
        batch_op.alter_column('meta_title',
               existing_type=sa.VARCHAR(length=70),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('meta_description',
               existing_type=sa.VARCHAR(length=160),
               type_=sa.String(length=250),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.alter_column('meta_description',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=160),
               existing_nullable=True)
        batch_op.alter_column('meta_title',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=70),
               existing_nullable=True)
        batch_op.drop_column('nome_comercial')

    # ### end Alembic commands ###
