"""Add guia transito estoque

Revision ID: ffeeb56c244c
Revises: 01801562760d
Create Date: 2025-11-27 17:47:05.883355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffeeb56c244c'
down_revision = '01801562760d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estoque_itens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guia_transito_file', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('numero_selo', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estoque_itens', schema=None) as batch_op:
        batch_op.drop_column('numero_selo')
        batch_op.drop_column('guia_transito_file')

    # ### end Alembic commands ###
